apiVersion: apps/v1
kind: Deployment
metadata:
  name: nest-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nest-app
  template:
    metadata:
      labels:
        app: nest-app
    spec:
      containers:
      - name: nest-app
        image: sharafreggui/nest-app:lastest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nest-app
spec:
  selector:
    app: nest-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
